=== umirbek-03/git-new/src/main/java/org/example/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="genreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Роман"/>
            <xs:enumeration value="Фантастика"/>
            <xs:enumeration value="Детектив"/>
            <xs:enumeration value="Поэзия"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1500"/>
                        <xs:maxInclusive value="2025"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="genre" type="genreType"/>
            <xs:element name="price">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="100"/>
                        <xs:maxInclusive value="10000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="bookType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== umirbek-03/git-new/src/main/java/org/example/mainxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
    <book id="1">
        <title >Война и мир</title>
        <author>Лев Толстой</author>
        <year>1869</year>
        <genre>Роман</genre>
        <price>500</price>
    </book>
    <book id="2">
        <title>Преступление и наказание</title>
        <author>Федор Достоевский</author>
        <year>1866</year>
        <genre>Детектив</genre>
        <price>400</price>
    </book>
</library>
